services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: flexilearn
    ports:
      - "5432:5432"
    volumes:
      - postgres_flexilearn:/var/lib/postgresql

  piston:
    image: ghcr.io/engineer-man/piston
    container_name: piston_api
    privileged: true
    ports:
      - 2000:2000
    volumes:
      - ./data/piston/packages:/piston/packages
    tmpfs:
      - /tmp:exec
volumes:
  postgres_flexilearn:
